apiVersion: argoproj.io/v1alpha1
kind: Application


metadata:

  name: ai

  namespace: argocd


  annotations:

    argocd.argoproj.io/sync-wave: "50"


spec:

  project: default


  source:

    repoURL: REPLACE_REPO_URL

    targetRevision: REPLACE_BRANCH

    path: apps/ai


  destination:

    server: https://kubernetes.default.svc

    namespace: argocd


  syncPolicy:

    automated:

      prune: true

      selfHeal: true