ingresses:

  - name: argocd
    path: bootstrap/argocd/ingress.yaml
    subdomain: argocd

  - name: rancher
    path: apps/infrastructure/rancher/resources/ingress.yaml
    subdomain: rancher

  - name: rancher-hostname
    path: apps/infrastructure/rancher/values.yaml
    subdomain: rancher

  - name: longhorn
    path: apps/infrastructure/longhorn/resources/ingress.yaml
    subdomain: longhorn

  - name: qbittorrent
    path: apps/infrastructure/qbittorrent/resources/ingress.yaml
    subdomain: qbittorrent

  - name: wg-easy
    path: apps/infrastructure/wg-easy/resources/ingress.yaml
    subdomain: wg

# ADDING NEW ONES EXAMPLE:
#  - name: grafana
#    path: apps/infrastructure/monitoring/resources/grafana-ingress.yaml
#    subdomain: grafana