kubeProxyReplacement: true

k8sServiceHost: 192.168.50.222 ## Change to Your VIP 

k8sServicePort: 6443

operator:
  replicas: 2

ipam:
  mode: kubernetes

routingMode: native

autoDirectNodeRoutes: true

bpf:
  masquerade: true

rollOutPods: true
