apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cert-manager
  namespace: argocd

spec:

  project: homelab

  sources:

    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.2

      helm:
        valueFiles:
          - $values/apps/infrastructure/cert-manager/values.yaml


    - repoURL: REPLACE_ME
      targetRevision: main
      ref: values


  destination:

    server: https://kubernetes.default.svc
    namespace: cert-manager


  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true