apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - cert-manager/app.yaml
  - longhorn/app.yaml
  - ingress-nginx/app.yaml
  - metrics-server/app.yaml
  - metallb/app.yaml
  - node-feature-discovery/app.yaml
  - rancher/app.yaml
  - qbittorrent/app.yaml
  - wg-easy/app.yaml   # removed by the GitOps sync when vpn.enabled is false
